[bump]
initial_tag = "1.0-alpha1"

[changelog]
header = """
# Changelog\n
All notable changes to this project will be documented in this file.\n
"""
body = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{% macro print_commit(commit) -%}
    - {% if commit.scope %}**{{ commit.scope }}**: {% endif %}\
        {% if commit.breaking %}[**breaking**] {% endif %}\
        {{ commit.message }} \
        ([{{ commit.id | truncate(length=7, end="") }}]({{ self::remote_url() }}/commit/{{ commit.id }}))\
{% endmacro -%}

{% if version %}\
    {% if previous.version %}\
        ## [{{ version | trim_start_matches(pat="v") }}]\
          ({{ self::remote_url() }}/compare/{{ previous.version }}..{{ version }})  â€”  {{ timestamp | date(format="%Y-%m-%d") }}
    {% else %}\
        ## {{ version | trim_start_matches(pat="v") }}  â€”  {{ timestamp | date(format="%Y-%m-%d") }}
    {% endif %}\
{% else %}\
    ## [unreleased]
{% endif %}\

{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits | filter(attribute="scope") | sort(attribute="scope") %}
        {{ self::print_commit(commit=commit) }}
    {%- endfor %}
    {% for commit in commits %}
        {%- if not commit.scope -%}
            {{ self::print_commit(commit=commit) }}
        {% endif -%}
    {% endfor -%}
{% endfor %}


"""

[git]
skip_tags = "(0\\.0\\.\\d)|1\\.0\\.0-alpha\\.1"
commit_parsers = [
	{ field = "breaking", pattern = "true", group = "<!-- -1 -->ğŸš¨ Breaking changes" },
	{ message = "^feat", group = "<!-- 0 -->ğŸš€ Features" },
	{ message = "^perf", group = "<!-- 1 -->âš¡ Performance" },
	{ message = "^fix", group = "<!-- 2 -->ğŸ› Bug fixes" },
	{ body = ".*security", group = "<!-- 3 -->ğŸ›¡ï¸ Security" },
	{ message = "^revert", group = "<!-- 4 -->âª Revert" },
	{ message = "^docs", group = "<!-- 5 -->ğŸ“š Documentation", skip = true },
	{ message = "^refactor", group = "<!-- 6 -->ğŸšœ Refactor", skip = true },
	{ message = "^test", group = "<!-- 7 -->ğŸ§ª Tests", skip = true },
	{ message = "^style", skip = true },
	{ message = "^chore|^ci", skip = true },
]
