name: Coding Conventions

on:
  pull_request:
  workflow_dispatch:

# CSFixer and Rector are temporarily disabled until they have proper PHP 8.4 support
jobs:
 check-style:
    name: Run style check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction

      - name: Setup Mago 
        uses: nhedger/setup-mago@v1

      - name: Run Mago 
        run: |
          mago fmt --dry-run
          mago lint --reporting-format=github

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run ESLint
        run: bun run lint

 phpstan:
    name: "Run static analysis: PHPStan"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3

      - name: Run PHPStan
        run: vendor/bin/phpstan --error-format=github

#  rector:
#    name: "Run static analysis: Rector"
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Setup PHP
#        uses: shivammathur/setup-php@v2
#        with:
#          php-version: 8.4
#          coverage: none
#
#      - name: Install composer dependencies
#        uses: ramsey/composer-install@v3
#
#      - name: Run Rector
#        run: vendor/bin/rector process --no-ansi --dry-run --no-progress-bar
